name: Docker Publish

# 触发条件：当代码推送到 main 分支时运行
on:
  push:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 Docker Buildx，这是一个增强的构建工具
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. 登录到 GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. 构建并推送后端镜像
      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./TestRunner_Django
          file: ./TestRunner_Django/Dockerfile
          push: true
          tags: ghcr.io/lucky-testrunner/testrunner-backend:latest

      # 5. 构建并推送前端镜像
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./TestRunner_Vue
          file: ./TestRunner_Vue/Dockerfile
          push: true
          tags: ghcr.io/lucky-testrunner/testrunner-frontend:latest